Vagrant.configure("2") do |config|
  
    config.vm.define "k8smaster" do |k8smaster|
      k8smaster.vm.box_download_insecure = true
      k8smaster.vm.box = "ubuntu/trusty64"
      k8smaster.vm.network "private_network", ip: "100.0.0.2"
      k8smaster.vm.hostname = "k8smaster"
      k8smaster.vm.provider "virtualbox" do |v|
        v.name = "k8smaster"
        v.memory = 2048
        v.cpus = 2
      end
    end
  
    config.vm.define "Node1" do |k8smaster|
      k8smaster.vm.box_download_insecure = true
      k8smaster.vm.box = "ubuntu/trusty64"
      k8smaster.vm.network "private_network", ip: "100.0.0.2"
      k8smaster.vm.hostname = "Node1"
      k8smaster.vm.provider "virtualbox" do |v|
        v.name = "WorkerNode1"
        v.memory = 2048
        v.cpus = 2
      end
    end
  
  
    config.vm.define "Node2" do |k8sworker|
      k8sworker.vm.box_download_insecure = true
      k8sworker.vm.box = "ubuntu/trusty64"
      k8sworker.vm.network "private_network", ip: "100.0.0.3"
      k8sworker.vm.hostname = "Node2"
      k8sworker.vm.provider "virtualbox" do |v|
        v.name = "Node2"
        v.memory = 2048
        v.cpus = 2
      end
    end
  end