apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
   app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: akpaul1991/app:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    app: app1
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: app1
