--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    run: my-nginx
  name: my-nginx
spec: 
  ports: 
    - 
      name: http
      nodePort: 30080
      port: 8080
      protocol: TCP
      targetPort: 80
  selector: 
    run: my-nginx
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      volumes:
      - name: configmap-volume
        configMap:
          name: nginxconfigmap
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume